package com.mszq.uas.syncdata.mode;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table uas_role
 *
 * @mbg.generated do_not_delete_during_merge Fri Mar 22 13:43:44 CST 2019
 */
public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_role.ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_role.ROLE_NAME
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_role.ROLE_CODE
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_role.STATUS
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_role.ORG_ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_role.ORG_TYPE
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    private Short orgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_role.PARENT_ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_role.ROLE_TYPE_ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    private Integer roleTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_role.COMMENT
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_role.MODIFY_TIME
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    private Date modifyTime;

    private int leaderRoleId;

    public int getLeaderRoleId() {
        return leaderRoleId;
    }

    public void setLeaderRoleId(int leaderRoleId) {
        this.leaderRoleId = leaderRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_role.ID
     *
     * @return the value of uas_role.ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_role.ID
     *
     * @param id the value for uas_role.ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_role.ROLE_NAME
     *
     * @return the value of uas_role.ROLE_NAME
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_role.ROLE_NAME
     *
     * @param roleName the value for uas_role.ROLE_NAME
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_role.ROLE_CODE
     *
     * @return the value of uas_role.ROLE_CODE
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_role.ROLE_CODE
     *
     * @param roleCode the value for uas_role.ROLE_CODE
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_role.STATUS
     *
     * @return the value of uas_role.STATUS
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_role.STATUS
     *
     * @param status the value for uas_role.STATUS
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_role.ORG_ID
     *
     * @return the value of uas_role.ORG_ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_role.ORG_ID
     *
     * @param orgId the value for uas_role.ORG_ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_role.ORG_TYPE
     *
     * @return the value of uas_role.ORG_TYPE
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public Short getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_role.ORG_TYPE
     *
     * @param orgType the value for uas_role.ORG_TYPE
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public void setOrgType(Short orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_role.PARENT_ID
     *
     * @return the value of uas_role.PARENT_ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_role.PARENT_ID
     *
     * @param parentId the value for uas_role.PARENT_ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_role.ROLE_TYPE_ID
     *
     * @return the value of uas_role.ROLE_TYPE_ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public Integer getRoleTypeId() {
        return roleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_role.ROLE_TYPE_ID
     *
     * @param roleTypeId the value for uas_role.ROLE_TYPE_ID
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public void setRoleTypeId(Integer roleTypeId) {
        this.roleTypeId = roleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_role.COMMENT
     *
     * @return the value of uas_role.COMMENT
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_role.COMMENT
     *
     * @param comment the value for uas_role.COMMENT
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_role.MODIFY_TIME
     *
     * @return the value of uas_role.MODIFY_TIME
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_role.MODIFY_TIME
     *
     * @param modifyTime the value for uas_role.MODIFY_TIME
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}