package com.mszq.uas.sso.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table UAS_ACCOUNT
 *
 * @mbg.generated do_not_delete_during_merge Wed Nov 28 15:48:47 CST 2018
 */
public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ACCOUNT.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ACCOUNT.ACCOUNT_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Short accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ACCOUNT.STATUS
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ACCOUNT.CREATE_TIME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ACCOUNT.MODIFY_TIME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ACCOUNT.USER_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ACCOUNT.ID
     *
     * @return the value of UAS_ACCOUNT.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ACCOUNT.ID
     *
     * @param id the value for UAS_ACCOUNT.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ACCOUNT.ACCOUNT_ID
     *
     * @return the value of UAS_ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ACCOUNT.ACCOUNT_ID
     *
     * @param accountId the value for UAS_ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ACCOUNT.ACCOUNT_TYPE
     *
     * @return the value of UAS_ACCOUNT.ACCOUNT_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Short getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ACCOUNT.ACCOUNT_TYPE
     *
     * @param accountType the value for UAS_ACCOUNT.ACCOUNT_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setAccountType(Short accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ACCOUNT.STATUS
     *
     * @return the value of UAS_ACCOUNT.STATUS
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ACCOUNT.STATUS
     *
     * @param status the value for UAS_ACCOUNT.STATUS
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ACCOUNT.CREATE_TIME
     *
     * @return the value of UAS_ACCOUNT.CREATE_TIME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ACCOUNT.CREATE_TIME
     *
     * @param createTime the value for UAS_ACCOUNT.CREATE_TIME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ACCOUNT.MODIFY_TIME
     *
     * @return the value of UAS_ACCOUNT.MODIFY_TIME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ACCOUNT.MODIFY_TIME
     *
     * @param modifyTime the value for UAS_ACCOUNT.MODIFY_TIME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ACCOUNT.USER_ID
     *
     * @return the value of UAS_ACCOUNT.USER_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ACCOUNT.USER_ID
     *
     * @param userId the value for UAS_ACCOUNT.USER_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}