package com.mszq.uas.sso.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table UAS_IP_LIST
 *
 * @mbg.generated do_not_delete_during_merge Wed Nov 28 15:48:47 CST 2018
 */
public class IpList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_IP_LIST.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_IP_LIST.IP
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_IP_LIST.STATUS
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_IP_LIST.ID
     *
     * @return the value of UAS_IP_LIST.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_IP_LIST.ID
     *
     * @param id the value for UAS_IP_LIST.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_IP_LIST.IP
     *
     * @return the value of UAS_IP_LIST.IP
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_IP_LIST.IP
     *
     * @param ip the value for UAS_IP_LIST.IP
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_IP_LIST.STATUS
     *
     * @return the value of UAS_IP_LIST.STATUS
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_IP_LIST.STATUS
     *
     * @param status the value for UAS_IP_LIST.STATUS
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}