package com.mszq.uas.sso.model;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table UAS_LOG
 *
 * @mbg.generated do_not_delete_during_merge Wed Nov 28 15:48:47 CST 2018
 */
public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.OPER_TIME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Date operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.OPER_COMMENT
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String operComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.LOGIN_IP
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.USER_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.ACCOUNT_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.ACCOUNT_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Short accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.APP_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.LAST_LOGIN_MAC
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String lastLoginMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.LAST_LOGIN_INFO
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String lastLoginInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_LOG.LAST_LOGIN_IP
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String lastLoginIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.ID
     *
     * @return the value of UAS_LOG.ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.ID
     *
     * @param id the value for UAS_LOG.ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.OPER_TIME
     *
     * @return the value of UAS_LOG.OPER_TIME
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.OPER_TIME
     *
     * @param operTime the value for UAS_LOG.OPER_TIME
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.OPER_COMMENT
     *
     * @return the value of UAS_LOG.OPER_COMMENT
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getOperComment() {
        return operComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.OPER_COMMENT
     *
     * @param operComment the value for UAS_LOG.OPER_COMMENT
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setOperComment(String operComment) {
        this.operComment = operComment == null ? null : operComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.LOGIN_IP
     *
     * @return the value of UAS_LOG.LOGIN_IP
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.LOGIN_IP
     *
     * @param loginIp the value for UAS_LOG.LOGIN_IP
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.USER_ID
     *
     * @return the value of UAS_LOG.USER_ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.USER_ID
     *
     * @param userId the value for UAS_LOG.USER_ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.ACCOUNT_ID
     *
     * @return the value of UAS_LOG.ACCOUNT_ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.ACCOUNT_ID
     *
     * @param accountId the value for UAS_LOG.ACCOUNT_ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.ACCOUNT_TYPE
     *
     * @return the value of UAS_LOG.ACCOUNT_TYPE
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Short getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.ACCOUNT_TYPE
     *
     * @param accountType the value for UAS_LOG.ACCOUNT_TYPE
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setAccountType(Short accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.APP_ID
     *
     * @return the value of UAS_LOG.APP_ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.APP_ID
     *
     * @param appId the value for UAS_LOG.APP_ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.LAST_LOGIN_MAC
     *
     * @return the value of UAS_LOG.LAST_LOGIN_MAC
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getLastLoginMac() {
        return lastLoginMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.LAST_LOGIN_MAC
     *
     * @param lastLoginMac the value for UAS_LOG.LAST_LOGIN_MAC
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setLastLoginMac(String lastLoginMac) {
        this.lastLoginMac = lastLoginMac == null ? null : lastLoginMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.LAST_LOGIN_INFO
     *
     * @return the value of UAS_LOG.LAST_LOGIN_INFO
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getLastLoginInfo() {
        return lastLoginInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.LAST_LOGIN_INFO
     *
     * @param lastLoginInfo the value for UAS_LOG.LAST_LOGIN_INFO
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setLastLoginInfo(String lastLoginInfo) {
        this.lastLoginInfo = lastLoginInfo == null ? null : lastLoginInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_LOG.LAST_LOGIN_IP
     *
     * @return the value of UAS_LOG.LAST_LOGIN_IP
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_LOG.LAST_LOGIN_IP
     *
     * @param lastLoginIp the value for UAS_LOG.LAST_LOGIN_IP
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }
}