package com.mszq.uas.sso.model;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table UAS_ROLE_TYPE
 *
 * @mbg.generated do_not_delete_during_merge Wed Nov 28 15:48:47 CST 2018
 */
public class RoleType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ROLE_TYPE.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ROLE_TYPE.NAME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ROLE_TYPE.COMMENT
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ROLE_TYPE.ID
     *
     * @return the value of UAS_ROLE_TYPE.ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ROLE_TYPE.ID
     *
     * @param id the value for UAS_ROLE_TYPE.ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ROLE_TYPE.NAME
     *
     * @return the value of UAS_ROLE_TYPE.NAME
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ROLE_TYPE.NAME
     *
     * @param name the value for UAS_ROLE_TYPE.NAME
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ROLE_TYPE.COMMENT
     *
     * @return the value of UAS_ROLE_TYPE.COMMENT
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ROLE_TYPE.COMMENT
     *
     * @param comment the value for UAS_ROLE_TYPE.COMMENT
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}