package com.mszq.uas.sso.model;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table UAS_ROLE_APP
 *
 * @mbg.generated do_not_delete_during_merge Wed Nov 28 15:48:47 CST 2018
 */
public class RoleApp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ROLE_APP.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ROLE_APP.ROLE_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ROLE_APP.APP_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long appId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ROLE_APP.ID
     *
     * @return the value of UAS_ROLE_APP.ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ROLE_APP.ID
     *
     * @param id the value for UAS_ROLE_APP.ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ROLE_APP.ROLE_ID
     *
     * @return the value of UAS_ROLE_APP.ROLE_ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ROLE_APP.ROLE_ID
     *
     * @param roleId the value for UAS_ROLE_APP.ROLE_ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ROLE_APP.APP_ID
     *
     * @return the value of UAS_ROLE_APP.APP_ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ROLE_APP.APP_ID
     *
     * @param appId the value for UAS_ROLE_APP.APP_ID
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }
}