package com.mszq.uas.uasserver.dao.mapper;

import com.mszq.uas.uasserver.dao.model.Account;
import com.mszq.uas.uasserver.dao.model.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    long countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    Account selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_account
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByPrimaryKey(Account record);
}