package com.mszq.uas.uasserver.dao.mapper;

import com.mszq.uas.uasserver.dao.model.App;
import com.mszq.uas.uasserver.dao.model.AppExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

@Repository
public interface AppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    long countByExample(AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int deleteByExample(AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int insert(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int insertSelective(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    List<App> selectByExample(AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    App selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") App record, @Param("example") AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByExample(@Param("record") App record, @Param("example") AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByPrimaryKeySelective(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_app
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByPrimaryKey(App record);

    @Select("SELECT * FROM UAS_APP")
    List<App> selectAll();
}