package com.mszq.uas.uasserver.dao.mapper;

import com.mszq.uas.uasserver.dao.model.Org;
import com.mszq.uas.uasserver.dao.model.OrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface OrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    long countByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    int deleteByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    int insert(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    int insertSelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    List<Org> selectByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    Org selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") Org record, @Param("example") OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    int updateByExample(@Param("record") Org record, @Param("example") OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    int updateByPrimaryKeySelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org
     *
     * @mbg.generated Mon Mar 18 18:03:54 CST 2019
     */
    int updateByPrimaryKey(Org record);
}