package com.mszq.uas.uasserver.dao.mapper;

import com.mszq.uas.uasserver.dao.model.OrgType;
import com.mszq.uas.uasserver.dao.model.OrgTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface OrgTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    long countByExample(OrgTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int deleteByExample(OrgTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int insert(OrgType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int insertSelective(OrgType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    List<OrgType> selectByExample(OrgTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    OrgType selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrgType record, @Param("example") OrgTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByExample(@Param("record") OrgType record, @Param("example") OrgTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByPrimaryKeySelective(OrgType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_org_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByPrimaryKey(OrgType record);
}