package com.mszq.uas.uasserver.dao.mapper;

import com.mszq.uas.uasserver.dao.model.Password;
import com.mszq.uas.uasserver.dao.model.PasswordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface PasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    long countByExample(PasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int deleteByExample(PasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int insert(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int insertSelective(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    List<Password> selectByExample(PasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    Password selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") Password record, @Param("example") PasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByExample(@Param("record") Password record, @Param("example") PasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByPrimaryKeySelective(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_password
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByPrimaryKey(Password record);
}