package com.mszq.uas.uasserver.dao.mapper;

import com.mszq.uas.uasserver.dao.model.Role;
import com.mszq.uas.uasserver.dao.model.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

@Repository
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role
     *
     * @mbg.generated Fri Mar 22 13:43:44 CST 2019
     */
    int updateByPrimaryKey(Role record);

    @Select("SELECT * FROM UAS_ROLE WHERE FIND_IN_SET(ID, getChildList(#{roleId}))")
    List<Role> selectAllChildrenRole(@Param("roleId") Long roleId);

    @Select("SELECT * FROM UAS_ROLE WHERE FIND_IN_SET(ID, getParentList(#{roleId}))")
    List<Role> selectAllParentRole(@Param("roleId") Long roleId);

    @Select("SELECT ID FROM UAS_ROLE WHERE FIND_IN_SET(ID, getParentList(#{roleId}))")
    List<Long> selectAllParentRoleIds(@Param("roleId") Long roleId);
}