package com.mszq.uas.uasserver.dao.mapper;

import com.mszq.uas.uasserver.dao.model.RoleApp;
import com.mszq.uas.uasserver.dao.model.RoleAppExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RoleAppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    long countByExample(RoleAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int deleteByExample(RoleAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int insert(RoleApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int insertSelective(RoleApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    List<RoleApp> selectByExample(RoleAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    RoleApp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") RoleApp record, @Param("example") RoleAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByExample(@Param("record") RoleApp record, @Param("example") RoleAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByPrimaryKeySelective(RoleApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_app
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    int updateByPrimaryKey(RoleApp record);
}