package com.mszq.uas.uasserver.dao.mapper;

import com.mszq.uas.uasserver.dao.model.Role;
import com.mszq.uas.uasserver.dao.model.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAS_ROLE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    int updateByPrimaryKey(Role record);
}