package com.mszq.uas.uasserver.dao.mapper;

import com.mszq.uas.uasserver.dao.model.RoleType;
import com.mszq.uas.uasserver.dao.model.RoleTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RoleTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    long countByExample(RoleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int deleteByExample(RoleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int insert(RoleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int insertSelective(RoleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    List<RoleType> selectByExample(RoleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    RoleType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") RoleType record, @Param("example") RoleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByExample(@Param("record") RoleType record, @Param("example") RoleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByPrimaryKeySelective(RoleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uas_role_type
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    int updateByPrimaryKey(RoleType record);
}