package com.mszq.uas.uasserver.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table UAS_APP
 *
 * @mbg.generated do_not_delete_during_merge Wed Nov 28 15:48:47 CST 2018
 */
public class App {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP.NAME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP.SECRET
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP.ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Short orgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP.PATH
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP.COMMENT
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP.ID
     *
     * @return the value of UAS_APP.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP.ID
     *
     * @param id the value for UAS_APP.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP.NAME
     *
     * @return the value of UAS_APP.NAME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP.NAME
     *
     * @param name the value for UAS_APP.NAME
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP.SECRET
     *
     * @return the value of UAS_APP.SECRET
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP.SECRET
     *
     * @param secret the value for UAS_APP.SECRET
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP.ORG_TYPE
     *
     * @return the value of UAS_APP.ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Short getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP.ORG_TYPE
     *
     * @param orgType the value for UAS_APP.ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setOrgType(Short orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP.PATH
     *
     * @return the value of UAS_APP.PATH
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP.PATH
     *
     * @param path the value for UAS_APP.PATH
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP.COMMENT
     *
     * @return the value of UAS_APP.COMMENT
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP.COMMENT
     *
     * @param comment the value for UAS_APP.COMMENT
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}