package com.mszq.uas.uasserver.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table UAS_APP_ACCOUNT
 *
 * @mbg.generated do_not_delete_during_merge Wed Nov 28 15:48:47 CST 2018
 */
public class AppAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP_ACCOUNT.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP_ACCOUNT.APP_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP_ACCOUNT.ORG_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP_ACCOUNT.ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Short orgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP_ACCOUNT.USER_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP_ACCOUNT.JOB_NUMBER
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String jobNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_APP_ACCOUNT.ACCOUNT
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private String account;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP_ACCOUNT.ID
     *
     * @return the value of UAS_APP_ACCOUNT.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP_ACCOUNT.ID
     *
     * @param id the value for UAS_APP_ACCOUNT.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP_ACCOUNT.APP_ID
     *
     * @return the value of UAS_APP_ACCOUNT.APP_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP_ACCOUNT.APP_ID
     *
     * @param appId the value for UAS_APP_ACCOUNT.APP_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP_ACCOUNT.ORG_ID
     *
     * @return the value of UAS_APP_ACCOUNT.ORG_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP_ACCOUNT.ORG_ID
     *
     * @param orgId the value for UAS_APP_ACCOUNT.ORG_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP_ACCOUNT.ORG_TYPE
     *
     * @return the value of UAS_APP_ACCOUNT.ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Short getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP_ACCOUNT.ORG_TYPE
     *
     * @param orgType the value for UAS_APP_ACCOUNT.ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setOrgType(Short orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP_ACCOUNT.USER_ID
     *
     * @return the value of UAS_APP_ACCOUNT.USER_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP_ACCOUNT.USER_ID
     *
     * @param userId the value for UAS_APP_ACCOUNT.USER_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP_ACCOUNT.JOB_NUMBER
     *
     * @return the value of UAS_APP_ACCOUNT.JOB_NUMBER
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP_ACCOUNT.JOB_NUMBER
     *
     * @param jobNumber the value for UAS_APP_ACCOUNT.JOB_NUMBER
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber == null ? null : jobNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_APP_ACCOUNT.ACCOUNT
     *
     * @return the value of UAS_APP_ACCOUNT.ACCOUNT
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_APP_ACCOUNT.ACCOUNT
     *
     * @param account the value for UAS_APP_ACCOUNT.ACCOUNT
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }
}