package com.mszq.uas.uasserver.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table uas_ip_list
 *
 * @mbg.generated do_not_delete_during_merge Thu Nov 22 17:14:59 CST 2018
 */
public class IpList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_ip_list.ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_ip_list.IP
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_ip_list.STATUS
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_ip_list.ID
     *
     * @return the value of uas_ip_list.ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_ip_list.ID
     *
     * @param id the value for uas_ip_list.ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_ip_list.IP
     *
     * @return the value of uas_ip_list.IP
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_ip_list.IP
     *
     * @param ip the value for uas_ip_list.IP
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_ip_list.STATUS
     *
     * @return the value of uas_ip_list.STATUS
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_ip_list.STATUS
     *
     * @param status the value for uas_ip_list.STATUS
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}