package com.mszq.uas.uasserver.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table UAS_ORG_ID_MAP
 *
 * @mbg.generated do_not_delete_during_merge Wed Nov 28 15:48:47 CST 2018
 */
public class OrgIdMap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ORG_ID_MAP.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ORG_ID_MAP.SROUCE_ORG_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long srouceOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ORG_ID_MAP.SROUCE_ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Short srouceOrgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ORG_ID_MAP.TARGET_ORG_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Long targetOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAS_ORG_ID_MAP.TARGET_ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    private Short targetOrgType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ORG_ID_MAP.ID
     *
     * @return the value of UAS_ORG_ID_MAP.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ORG_ID_MAP.ID
     *
     * @param id the value for UAS_ORG_ID_MAP.ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ORG_ID_MAP.SROUCE_ORG_ID
     *
     * @return the value of UAS_ORG_ID_MAP.SROUCE_ORG_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getSrouceOrgId() {
        return srouceOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ORG_ID_MAP.SROUCE_ORG_ID
     *
     * @param srouceOrgId the value for UAS_ORG_ID_MAP.SROUCE_ORG_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setSrouceOrgId(Long srouceOrgId) {
        this.srouceOrgId = srouceOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ORG_ID_MAP.SROUCE_ORG_TYPE
     *
     * @return the value of UAS_ORG_ID_MAP.SROUCE_ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Short getSrouceOrgType() {
        return srouceOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ORG_ID_MAP.SROUCE_ORG_TYPE
     *
     * @param srouceOrgType the value for UAS_ORG_ID_MAP.SROUCE_ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setSrouceOrgType(Short srouceOrgType) {
        this.srouceOrgType = srouceOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ORG_ID_MAP.TARGET_ORG_ID
     *
     * @return the value of UAS_ORG_ID_MAP.TARGET_ORG_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Long getTargetOrgId() {
        return targetOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ORG_ID_MAP.TARGET_ORG_ID
     *
     * @param targetOrgId the value for UAS_ORG_ID_MAP.TARGET_ORG_ID
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setTargetOrgId(Long targetOrgId) {
        this.targetOrgId = targetOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAS_ORG_ID_MAP.TARGET_ORG_TYPE
     *
     * @return the value of UAS_ORG_ID_MAP.TARGET_ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public Short getTargetOrgType() {
        return targetOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAS_ORG_ID_MAP.TARGET_ORG_TYPE
     *
     * @param targetOrgType the value for UAS_ORG_ID_MAP.TARGET_ORG_TYPE
     *
     * @mbg.generated Wed Nov 28 15:48:47 CST 2018
     */
    public void setTargetOrgType(Short targetOrgType) {
        this.targetOrgType = targetOrgType;
    }
}