package com.mszq.uas.uasserver.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table uas_org_type
 *
 * @mbg.generated do_not_delete_during_merge Thu Nov 22 17:14:59 CST 2018
 */
public class OrgType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_org_type.ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_org_type.COMMENT
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_org_type.ID
     *
     * @return the value of uas_org_type.ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_org_type.ID
     *
     * @param id the value for uas_org_type.ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_org_type.COMMENT
     *
     * @return the value of uas_org_type.COMMENT
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_org_type.COMMENT
     *
     * @param comment the value for uas_org_type.COMMENT
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}