package com.mszq.uas.uasserver.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table uas_password
 *
 * @mbg.generated do_not_delete_during_merge Mon Nov 26 17:03:41 CST 2018
 */
public class Password {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_password.ID
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_password.USER_ID
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_password.PASSWORD
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_password.ID
     *
     * @return the value of uas_password.ID
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_password.ID
     *
     * @param id the value for uas_password.ID
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_password.USER_ID
     *
     * @return the value of uas_password.USER_ID
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_password.USER_ID
     *
     * @param userId the value for uas_password.USER_ID
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_password.PASSWORD
     *
     * @return the value of uas_password.PASSWORD
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_password.PASSWORD
     *
     * @param password the value for uas_password.PASSWORD
     *
     * @mbg.generated Mon Nov 26 17:03:41 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}