package com.mszq.uas.uasserver.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table uas_user_role
 *
 * @mbg.generated do_not_delete_during_merge Thu Nov 22 17:14:59 CST 2018
 */
public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_user_role.ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_user_role.USER_ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uas_user_role.ROLE_ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_user_role.ID
     *
     * @return the value of uas_user_role.ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_user_role.ID
     *
     * @param id the value for uas_user_role.ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_user_role.USER_ID
     *
     * @return the value of uas_user_role.USER_ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_user_role.USER_ID
     *
     * @param userId the value for uas_user_role.USER_ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uas_user_role.ROLE_ID
     *
     * @return the value of uas_user_role.ROLE_ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uas_user_role.ROLE_ID
     *
     * @param roleId the value for uas_user_role.ROLE_ID
     *
     * @mbg.generated Thu Nov 22 17:14:59 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}